### ISSUE TITLE
Cannot set up database

### ISSUE THREAD

**Issue by SGchongbooncheng** [kaushik546/Inventory-Management-System#3]
Hi do you have the ldf database file bcos you only provided the mdf file but the database need both mdf and ldf so that I can attach it to my own database. Thanks

**Comment by kaushik546** [comment]
@SGchongbooncheng I have just one database file ".mdf". You don't need ".ldf" file for this project because it is a supporting file and it stores the information related to transaction logs etc.

**Comment by SGchongbooncheng** [comment]
Hi it is not over yet. I tried to attach the mdf file to mssql but I cannot attach it to my database.
<img width="421" alt="Screenshot 2020-12-03 100710" src="https://user-images.githubusercontent.com/74750960/100954337-559d6900-354f-11eb-8348-77b33cb235bf.png">
